FROM alpine:3.8

RUN apk add --update \
    bind-tools \
    curl \
    git \
    htop \
    iotop \
    iputils \
    net-tools \
    strace \
    tcpdump \
    tree \
    vim \
    wget \
  && rm -rf /var/cache/apk/*
